name: Starting By revWhiteShadow

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Download and Install Resources
      run: |
        # Download and make the Playit agent executable
        curl -L "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-x86_64-signed" -o ~/playit
        chmod +x ~/playit
        sleep 5  # Give some time for the download to complete

    - name: Install and Configure RDP Server
      run: |
        # Update and install necessary packages for RDP
        sudo apt update
        sudo apt install -y xrdp pulseaudio

        # Enable and start the XRDP service
        sudo systemctl enable --now xrdp

        # Configure PulseAudio for RDP sound redirection
        sudo systemctl enable --now pulseaudio

        # Configure the RDP server to use the proper session
        sudo sed -i 's/3389/3390/' /etc/xrdp/xrdp.ini  # Optional: Change default RDP port if needed

        # Set the default RDP session to Ubuntu Desktop (or your preferred session)
        echo "exec /usr/bin/startxfce4" | sudo tee -a ~/.xsession

    - name: Set RDP Password
      run: |
        # Create user 'runneradmin' with a specified password
        sudo useradd -m runneradmin
        echo "runneradmin:revWS123!" | sudo chpasswd

    - name: Set Up RDP Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        # Start playit.gg with the provided authentication key
        ~/playit --secret $PLAYIT_AUTH_KEY &
        sleep 5  # Allow some time for the tunnel to establish

    - name: Keep the GitHub Action Runner Alive
      run: |
        # Keep the action running so that the RDP session remains active
        sleep 11800  # Adjust the duration based on your needs
