name: Starting By revWhiteShadow

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install Required Packages
      run: |
        sudo apt update
        sudo apt install -y xrdp pulseaudio

    - name: Enable Remote Desktop (RDP)
      run: |
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Set Up RDP Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        # Assuming playit is compatible with Ubuntu
        wget https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-x86_64-signed.tar.gz
        tar -xvzf playit-linux-x86_64-signed.tar.gz
        ./playit --secret $env:PLAYIT_AUTH_KEY &

    # Prevent workflow from stopping
    - name: Keep the GitHub Action Runner Alive
      run: |
        sleep 11800
