name: Starting By revWhiteShadow

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Download and Install Resources
      run: |
        curl -L "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-x86_64-signed" -o ~/playit
        chmod +x ~/playit
        sleep 5  # Give some time for the download to complete

    - name: Enable Remote Desktop (RDP) and Sound
      run: |
        sudo apt update
        sudo apt install -y xrdp pulseaudio
        sudo systemctl enable --now xrdp
        sudo systemctl enable --now pulseaudio

    - name: Set RDP Password
      run: |
        sudo useradd -m runneradmin
        echo "runneradmin:revWS123!" | sudo chpasswd

    - name: Set Up RDP Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        ~/playit --secret $PLAYIT_AUTH_KEY &
        sleep 5  # Allow some time for the tunnel to start

    # Prevent workflow from stopping
    - name: Keep the GitHub Action Runner Alive
      run: |
        sleep 11800  # Adjust the duration based on your needs
