name: Starting By revWhiteShadow

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Download and Install Resources
      run: |
        curl -L "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-x86_64-signed" -o ~/playit
        chmod +x ~/playit
        sleep 5  # Give some time for the download to complete

    - name: Enable Remote Desktop (RDP) and Sound
      run: |
        sudo apt update
        sudo apt install -y xrdp pulseaudio
        sudo systemctl enable --now xrdp
        sudo systemctl enable --now pulseaudio
    - name: Set RDP Password
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "revWS123!" -Force)

    - name: Set Up RDP Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow -Wait
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -NoNewWindow

    # Prevent workflow from stopping
    - name: Keep the GitHub Action Runner Alive
      run: |
        Start-Sleep -Seconds 11800  # Adjust the duration based on your needs

